export const AddressConstants = {
  COUNTRY_MAX_LENGTH: 100,
  STATE_MAX_LENGTH: 100,
  CITY_MAX_LENGTH: 100,
  ZIP_CODE_LENGTH: 8,
  STREET_MAX_LENGTH: 150,
  NUMBER_MAX_VALUE: 99999,
  NUMBER_MIN_VALUE: 1
};
