#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
  echo "Only commits with a type tag are allowed" >&2
  echo "Aborting commit" >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE ".{1,88}"; then
  echo "Commit message must be at least one character and at most 88 characters" >&2
  echo "Aborting commit" >&2
  exit 1
fi